### ISSUE TITLE
具体描述

### ISSUE THREAD

**Issue by ciweigg** [onlyeat3/dictator#3]
使用你的springboot，demo启动后服务端1S会刷新一次，集成到我的项目中1S不刷新 感觉什么没加载到。。我刷新功能没法用

**Comment by liuyuyu** [comment]
怕影响别的日志，客户端的日志级别比较低。把客户端的日志级别改成debug就能看到请求日志了

**Comment by ciweigg** [comment]
我现在的问题是，集成到自己项目中了，能获取到配置的值，但是无法刷新值。不知道为什么。。。

**Comment by liuyuyu** [comment]
@ciweigg 我本地跑了一遍，看着没啥问题，贴一下配置看看？
